language: java
sudo: true
dist: trusty
jdk:
  - oraclejdk15
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: cryptovaluebtc
  on:
    repo: pdrodavi/cryptocurrencies-app
