dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk15
script:
  - java --version
  - ./mvnw clean install
  - ./mvnw test
before_install:
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: cryptovaluebtc
  on:
    repo: pdrodavi/cryptocurrencies-app
