language: java
sudo: true
dist: trusty
jdk:
  - oraclejdk15
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: 4c18f47f-0f76-4a49-9be6-abde7e14a7f5
  app: cryptovaluebtc
  on:
    repo: pdrodavi/cryptocurrencies-app
