dist: trusty
language: java
sudo: true
addons:
  apt:
    packages:
      - openjdk-15-jdk
jdk:
  - openjdk15 
before_install:
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: $HEROKU_API_KEY
  app: cryptovaluebtc
