dist: trusty
language: java
sudo: true
jdk:
  - oraclejdk15
addons:
  apt:
    packages:
      - oracle-java15-installer
before_install:
  - add-apt-repository ppa:linuxuprising/java
  - apt update
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: $HEROKU_API_KEY
  app: cryptovaluebtc
